### ISSUE TITLE
Vlastní téma prvního úkolu

### ISSUE THREAD

**Issue by prihoda** [cvut/MI-PYT#10]
Ahoj, jaké funkce budeme rozvíjet u aplikace z prvního úkolu? Konfig soubor, napojení na API a pokud jsem slyšel dobře, příště to bude Streaming API a webové rozhraní?

Přemýšlím, že bych využil projekt na kterém pracuju, tak pokud by to sedělo, ozval bych se na mail.

**Comment by encukou** [comment]
Díky za otázku. S trochu představivosti (neboli hádání) to jde vyčíst z obsahu předmětu*, ale vždycky je to lepší mít explicitně:
1. Weboví klienti + CLI - aktuální zadání
2. Webové servery - materiály včetně zadání už jsou online; neměly by se zásadně měnit
3. Jak dělat moduly – vytvoření balíčku, který pak půjde nainstalovat pomocí `pip`, t.j. žádná nová funkcionalita
4. Testování – dopsání testů, což by mělo jít pro jakýkoliv projekt
5. Dokumentace – taky by měla jít pro jakýkoli projekt
6. a dál – v dalších lekcích na projekt navazovat nebudeme.

Čili: příště kolem projektu uděláme webovou aplikaci, která poběží někde v cloudu. V dalších úkolech pak samotnou funkcionalitu rozšiřovat nebudeme.

---

\*  obsah by měl být na Eduxu; @hroncok doplní odkaz; já teprve získávám přístup :)

**Comment by hroncok** [comment]
Osnova na Eduxu není, ale je v KOSu a v [bílé knize](http://bk.fit.cvut.cz/cz/predmety/00/00/00/00/00/00/04/87/12/p4871206.html).
