### ISSUE TITLE
Nejasna specifikacia chyboveho vystupu

### ISSUE THREAD

**Issue by klememi** [cvut/MI-PYT#102]
V zadani je napisane z v pripade chyb mame pouzit hlasku:
`SUMMARY: there were X errors, please error check log, (kód 10)`
A hned pod tym je priklad, kde je pouzita hlaska ina:
```
ERROR: UPD; MarekSuchanek/repo1; ABC; CCaXXF; 422 - Validation Failed
ERROR: LBL; MarekSuchanek/repo2; 404 - Not Found
ERROR: ADD; pyvec/naucse.python.cz; ABC; CCaXXF; 404 - Not Found
SUMMARY: 3 error(s) in total, please check log above
```
Ktore je spravne?

**Comment by MarekSuchanek** [comment]
Díky za report, správně je ten, který je všude jinde a v testech... fixed https://github.com/cvut/MI-PYT/commit/0326e8e82a237b6aef68748da1075bc4f95e0ad6
