### ISSUE TITLE
test_precedence_template_repo

### ISSUE THREAD

**Issue by HalfDeadPie** [cvut/MI-PYT#105]
Dobry den,
chcel by som sa spytat na test test_precedence_template_repo. Z testu mi vyplyva, ze ak pomocou --template-repo zadam repo, ktore je sice prazdne ale ma vyssiu prioritu ako repo v config subore, tak sa neaktualizuje ziadne ine repo, lebo template je prazdny.

Test ocakava 3x GET request ale zaroven aj 'SUMMARY: 2 repo(s) updated successfully', ale neviem prist na to ako tieto dve podmienky naraz splnit. Alebo som niečomu zle pochopil? Rovnaky problem mam v podstate aj pri teste test_update_empty_labels. Dakujem

**Comment by MarekSuchanek** [comment]
1. Konfigurace z argumentů/přepínačů má vyšší prioritu než z konfiguračního souboru.
2. Summary říká kolik repozitářů to zpracovalo (v případě, že nebyly chyby) a tím se rozumí i když se vyhodnotilo, že nejsou potřeba provést žádné změny (žádné štítky se nemusí přidávat, upravovat ani odstraňovat).

`test_run_tricky.py::test_precedence_template_repo` - první GET je za zjištění obsahu `MarekSuchanek/repo4` (template-repo) a další dva jsou za zjištění obsahů repozitářů z konfiguračního souboru `MarekSuchanek/repo1` a `MarekSuchanek/repo2`. Je pravda, že jestliže se jedná o `update` s prázdným seznamem štítků, tak by bylo možné to zoptimalizovat a rovnou skončit. Takhle je to ale zjednodušené, že se to chová stejně i pro mód `replace`. U testu `test_run_update.py::test_update_empty_labels` je to podobné.

Můžete si případně udělat dobrovolně navíc přepínač (flag) `-o/--optimize`, se kterým budou provedeny takovéto optimalizace...
