### ISSUE TITLE
[Pandas] Graf

### ISSUE THREAD

**Issue by klememi** [cvut/MI-PYT#109]
> Vykreslete graf, který pro každý jazyk ukáže průměrnou měsíční mzdu lidí z ČR/SR, kteří tento jazyk používají* (podle dat dostupných z dotazníku).

Tým `každý jazyk` sa myslí Python a Java alebo každý jazyk, ktorý Česi a Slováci uviedli?

**Comment by hroncok** [comment]
Podla mňa každý jazyk, ktorý Česi a Slováci uviedli. Ale viacej bude vedieť @encukou.

**Comment by klememi** [comment]
Ak áno, tak je to celkom nechutné. Alebo len nie som kamarát s Pandas-om..

**Comment by hroncok** [comment]
Výhoda Panadasu je v tom, že je to Python. V případě potřeby prostě můžeš sáhnout někam jinam. Koukni třeba na [`apply`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.apply.html).

**Comment by encukou** [comment]
Ano, pro každý jazyk, který Češi a Slováci uvedli. Omlouvám se za nepřesnost.

Souhlasím s tím, že vstupní data jsou v nechutném formátu – ale přece jen, čištění dat je většinou poměrně velká část té datové analýzy.
