### ISSUE TITLE
Nefungující pozvánky na spolupráci

### ISSUE THREAD

**Issue by encukou** [cvut/MI-PYT#11]
Od uživatelů @tulinkry a @slowbackspace mi přišly pozvánky na spolupráci na repozitářích, al tyto pozvánky mi nefungují. Předpokládám, že je to proto, že repozitář přejmenovali z něčeho jako "MI-PYT16" na opravdové jméno projektu – a stihli to dřív než jsem kliknul na pozvánku.

Můžete prosím pozvánku poslat znovu?

**Comment by tulinkry** [comment]
Opraveno

**Comment by encukou** [comment]
Díky!
