### ISSUE TITLE
Autentizace webhooku

### ISSUE THREAD

**Issue by vanclmil** [cvut/MI-PYT#111]
Ahoj, mám problém se získáním signature ze secretu.
Nezní to tak složitě - použít HMAC hexdigest s klíčem webhook secret, tělem requestu a sha1, nicméně mi to signature nevrací správný.
`hmac.new(cfg['github']['webhook_secret'].encode(), request.data, hashlib.sha1).hexdigest()`
Nenapadlo by vás někoho prosím, co dělám špatně?
Díky, Milan

**Comment by klememi** [comment]
ja som tiez skusal plno roznych moznosti, myslim, ze nebude vadit, ked poradim:
`hmac.new(bytes(secret, 'UTF-8'), msg=request.data, digestmod='sha1').hexdigest()`
funguje, porovnavanie potom robim pomocou `hmac.compare_digest()` (pozor! nesmies zabudnut pridat k hexdigestu na zaciatok `'sha1='`

**Comment by vanclmil** [comment]
Díky za tip, ale takhle mi to vrací to samý jako předtím, což je něco jinýho než je signature z hlavičky.

**Comment by klememi** [comment]
to je zaujimave, mne to funguje bez problemov. mozno budes mat chybu niekde inde?

**Comment by vanclmil** [comment]
Netušim kde by mohla být :D - akorát načtu secret z konfigu a ten potom použiju
`hmac.new(bytes(config_webhook_secret, 'UTF-8'), msg=r.data, digestmod='sha1')`
a hexdigest tohohle mi prostě nevrací stejný signature a nepříjde mi, že by to ještě něco mohlo ovlivňovat.

**Comment by ghost** [comment]
Nevím jestli je to tvůj případ ale přidám něco co jsem vy(řešil) já. 

PyCharm mi sám přidává end-line na konce souboru a přidal mi je, když jsem zkoumal co se jak posílá, do `tests_web/fixtures/data/pyplayground_label_created_webhook.json`

Pak pochopitelně neseděl ten podpis.

**Comment by vanclmil** [comment]
Nojo já jsem vlastně přeformátoval ty data když jsem je prohlížel. Tak to bude asi tím, good point, díky.
