### ISSUE TITLE
Tabulka s deadlines uloh na EDUXe

### ISSUE THREAD

**Issue by phandox** [cvut/MI-PYT#112]
Bolo by mozne vytvorit nejaku prehladnu tabulku s deadlinami uloh na EDUX? Viem ze kazda uloha ma 12 dni od zadania ale v zaplave uloh o tom mozem stratit prehlad.

Jasne mozem si ju spravit sam, radsej by som bol za oficialny zdroj terminom na centralizovanom mieste. Uplne idealne, daju sa deadlines uloh integrovat do [cvut/sirius](https://github.com/cvut/sirius) s naslednym exportom do kalendaru? Mozno dotaz priamo na @jirutka ?

Diky.

**Comment by encukou** [comment]
> Jasne mozem si ju spravit sam, radsej by som bol za oficialny zdroj terminom na centralizovanom mieste.

Chytnu tě za slovo :)

Když takovou tabulku uděláš v Markdownu <del>nebo HTML</del>, můžeš ji poslat jako pull request na [zdejší README](https://github.com/cvut/MI-PYT/blob/master/tutorials/00_uvod.md), a po kontrole se z ní stane onen oficiální zdroj.
Pokud nechceš, časem se k tomu dostaneme, ale alespoň pro mne to teď není úplně prioritní.

(A o Siriusu nic nevím.)

EDIT: HTML se nepřevede dobře. (@hroncok)

**Comment by hroncok** [comment]
Jinak centralizovaný systém deadlinů a export do Siria zajímal @balakzde.

**Comment by jirutka** [comment]
Sirius by neměl být _zdrojem_ dat o deadlinech, na to by měl vzniknout samostatný systém a do Siria ta data jen importovat. Měl jsem to už před lety v dlouhodobém plánu, ale nejsou lidi a peníze…

**Comment by hroncok** [comment]
@phandox uděláš tu tabulku?

**Comment by phandox** [comment]
@hroncok spis ne, moc volneho casu mi nezostava a delat to pro 1 semester bez nejakeho generatoru mi pride zbytecne , aby to bolo pouzitelne i dalsie semestre.

**Comment by hroncok** [comment]
Úlohy na https://courses.fit.cvut.cz/MI-PYT/tasks.html budou mít v nadpisech deadline.

Viz https://github.com/cvut/MI-PYT/pull/127

Považuju toto tedy za vyřešené.
