### ISSUE TITLE
Pandas - průměrný plat

### ISSUE THREAD

**Issue by vanclmil** [cvut/MI-PYT#113]
Ahoj,
jak je myšlen ten průměrný plat v úloze 3 - Pandas?
Všiml jsem si, že v datech je sloupec `Currency`, přičemž `Salary` je v právě udané mněně.
Podle mě nejde průměrovat různé mněny a tak jsem pracoval jen s Eury, jako s nejrelevantnějším zástupcem mněn.
@encukou Je to OK / je to jedno / nebo něco jiného?
Díky.
Milan

**Comment by encukou** [comment]
Všechna data máte k dispozici; musíte je nějak interpretovat. Na ta data se nedá spoléhat – lidem se mzda mění, lidi dostávají platy v různých měnách nebo obskurních měnách (jako CZK), lidi si špatně přečtou otázku, lidi lžou – ale pořád z toho jde něco vytáhnout.
Není tu jedna správná odpověď. 

Jestli po vyhození všeho kromě EUR zůstane relevantní výsledek, směle do toho! Jen prosím o stručné popsání metodiky (ta věta `Podle mě nejde průměrovat…` nahoře je OK) a zdůvodnění (proč je EUR nejrelevantnější?).

Pro lepší pochopení dat se může hodit PDFko, které jste s daty stáhli; pro tohle můžou být relevantní strany 1 (úvod) a 22 (zadání otázek pro `Currency` a `Salary`).

**Comment by BorisLaskov** [comment]
> We converted salaries given in the 38 most-frequently-used currencies to [dollars / Euros / pounds sterling] using the exchange rate that prevailed mid-way through the survey field period.

https://insights.stackoverflow.com/survey/2017

Taky spousta platu je ve floating pointu - proc by lide to uvadeli natolik presne? Nevim ted, kterou menu oni pouzili, ale, podle me, musi to byt nejak vyvazene.
