### ISSUE TITLE
Úloha moduly, konvence uvedené ve výukových materiálech

### ISSUE THREAD

**Issue by kravemir** [cvut/MI-PYT#115]
Ohľadom bodu zadania: 

> Musí splňovat konvence uvedené ve výukových materiálech.

Vo výukových materiáloch k modulom som našiel iba jedinú vetu obsahujúcu "konv...": 

> Všimněte si, že jsme balíček pojmenovali stejně jako soubor se zdrojovým kódem. Je to dobrá konvence, ale není to technicky nutné.

Bolo by lepšie, ak by boli materiály nejako štruktúrované, minimálne urobiť súhrn pre pojmy, na ktoré sa odkazuje zadanie, momentálne "konvence".

Alebo zadania kompletne definované, aby človek nemusel opakovane čítať celé materiály, a hľadať či v nejakých detailoch dlhého textu nebude niečo skryté, čo definuje nejaké konvence, aj bez priameho použitia slova "konvence".

**Comment by hroncok** [comment]
Zapracovávám přímo do zadání konkrétně specifikované věci. Díky za feedback.

**Comment by hroncok** [comment]
https://github.com/cvut/filabel/tree/modular#zad%C3%A1n%C3%AD-%C3%BAkolu-3
