### ISSUE TITLE
Testování výstupu click.echo

### ISSUE THREAD

**Issue by vanclmil** [cvut/MI-PYT#117]
Ahoj,
chtěl jsem se zeptat, jestli jde nějak v otestovat, zdali funkce dává správný výstup clicku.
Konkrétně funkce vypíše něco stylem `click.echo('cosi')` a já chci udělat test na to, jestli bylo vypsáno `'cosi'`.
Našel jsem jen řešení stylem přes `CliRunner().invoke()` s `result.output`, což ale nechci, protože chci udělat akorát jednotkový test té funkce.
Jde to nějak?
Díky

**Comment by hroncok** [comment]
Fixture capsys https://docs.pytest.org/en/stable/capture.html

**Comment by hroncok** [comment]
Taky se hodí [click.unstyle](http://click.pocoo.org/6/api/#click.unstyle) pokud píšeš barevně.

**Comment by hroncok** [comment]
Fixture capsys https://docs.pytest.org/en/stable/capture.html

Taky se hodí [click.unstyle](http://click.pocoo.org/6/api/#click.unstyle), pokud píšeš barevně.

```python
import click

def print_red_warning():
    click.secho('WARNING', fg='red')

def test_output_contains_exactly_warning(capsys):
    print_red_warning()
    out, err = capsys.readouterr()
    assert click.unstyle(out.strip()) == 'WARNING'
```

**Comment by vanclmil** [comment]
Jo díky, to jsem potřeboval.
