### ISSUE TITLE
Troubleshooting of Exception ignoring in Cython

### ISSUE THREAD

**Issue by ghost** [cvut/MI-PYT#119]
Exceptions were ignored at runtime and therefore tests were failing on this.

![image](https://user-images.githubusercontent.com/383295/32995544-3e4478a0-cd76-11e7-91f6-dbb5692c911b.png)

And finally, I have found this solution (**remove return type from function**) and explanation here: http://notes-on-cython.readthedocs.io/en/latest/misc.html#cdef-exceptions-and-the-return-type 

Maybe it will help also others. 
(I also suggest to include this in materials or homework hints.)

**Comment by hroncok** [comment]
Never tough this might be an issue, but it makes sense. Adding a note about better not to raise exceptions from cdef functions with return type sounds good. Will you be able to create a PR?

**Comment by encukou** [comment]
Spíš bych odkázal na [dokumentaci](http://cython.readthedocs.io/en/latest/src/reference/language_basics.html?highlight=exception#error-and-exception-handling) – dá se použít `except`/`except?`.
