### ISSUE TITLE
problem s jsonem

### ISSUE THREAD

**Issue by pilatcen** [cvut/MI-PYT#12]
Ahoj,

mám kód:

``` py
payload = '{"name": "bug", "color": "f29513"}'
print ("payload: "+payload)
r = session.post('https://api.github.com/repos/'+repo+'/issues/1/labels', data=payload)
pprint.pprint (r.json())
```

a github mi vrátí:

``` py
python3 robot.py 
payload: {"name": "bug", "color": "f29513"}
{'documentation_url': 'https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue',
 'message': 'Invalid request.\n'
            '\n'
            'For \'links/2/schema\', {"name"=>"bug", "color"=>"f29513"} is '
            'not an array.'}
```

Můžu poprosit o nakopnutí?
Díky

**Comment by slowbackspace** [comment]
V dokumentácií https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue pozri na sekciu "Input", to je to čo má isť do parametru data (list stringov, kde string je názov labelu).

**Comment by pilatcen** [comment]
Díky,
špatně jsem to pochopil, jel jsem podle tohoto: https://developer.github.com/v3/issues/labels/#create-a-label

**Comment by hroncok** [comment]
Z dokumentace to vypadá, že to očekává seznam názvů labelů a ne slovník s
názvem a barvou.
