### ISSUE TITLE
[Dokumentace] Readthedocs.org problem

### ISSUE THREAD

**Issue by IgorRosocha** [cvut/MI-PYT#121]
V rámci dokumentácie využívam extension _sphinx_click_ (https://github.com/click-contrib/sphinx-click). Lokálne funguje ako má, pokiaľ to uploadnem na readthedocs.org, build passne (http://labelord-igorrosocha.readthedocs.io/en/latest/), avšak kód, ktorý má zobrazovať tento extension, sa nezobrazí (konkrétne v tabe Usage). Kde môže byť problém? Extension je definovaný v conf.py, ako aj v requirements.txt.

**Comment by hroncok** [comment]
Podle logů to běží na Python 2.7. Možná bych začal tím. http://readthedocs.org/projects/labelord-igorrosocha/builds/6352663/

**Comment by hroncok** [comment]
Což má za následek nějaké výjimky při generování dokumentace.

**Comment by IgorRosocha** [comment]
bolo to ono, ani som si to nevšimol. Nenapadlo by ma, že Python interpreter bude defaultne nastavený na 2.x. Vďaka
