### ISSUE TITLE
Read-only přístup k repozitáři

### ISSUE THREAD

**Issue by chovanecm** [cvut/MI-PYT#16]
Ahoj, možná jsem něco přehlédl, ale jak můžu udělit někomu k privátnímu repozitáři přístup pouze pro čtení? Díky

**Comment by hroncok** [comment]
V osobním repozitáři ne. Je k tomu potřeba placený organizační účet, což jako studenti nemáte v rámci zdarma balíčku. My samozřejmě nic commitovat nebudeme.
