### ISSUE TITLE
Securing Github Webhooks

### ISSUE THREAD

**Issue by tulinkry** [cvut/MI-PYT#17]
Kdyby někdo hledal, jak funguje políčko `secret`:
https://developer.github.com/webhooks/securing/

**Comment by jirutka** [comment]
Ještě doplním příklad implementace, třeba se to někomu bude hodit: https://github.com/jirutka/github-pr-closer/blob/master/app.py.

**Comment by hroncok** [comment]
@tulinkry Uděláš prosím pullrequest do materiálů?
