### ISSUE TITLE
start aplikacie na pythonanywhere

### ISSUE THREAD

**Issue by lopatovsky** [cvut/MI-PYT#19]
Ahoj,
kde sa da prosim pythonanywhere nastavit, aby sa
aplikacia spustala z web commandom?
python3 twitter_wall.py web
....Error log:....
ImportError: No module named 'app'
....
na localhost-e funguje ok.
...
kostra kodu:

---

...
from flask import Flask
from flask import render_template
app = Flask(**name**)

@app.route('/')
@app.route('/<word>/')
def index(word=None):
 ....

@cli.command()
def web():
    app.run(debug=True) 

if **name** == '**main**':
    cli() 

---

dakujem!

**Comment by hroncok** [comment]
Je potřeba ze souboru _WSGI Configuration File_ naimportovat `app` jako `application`. O možnosti spuštění příkazem nevím.

**Comment by lopatovsky** [comment]
WSGI file tam uz je totozny ako na ukazke z hodiny.
Aplikacia fungovala na priklade "MI-PYT je najlepsi predmet ..."

**Comment by hroncok** [comment]
Ukaž prosím přesně, co máš v tom souboru ty (v ukázce z hodiny jsou nějaké placeholdery). Podívám se do tvého repa a pokusím se zjistit, proč to nefunguje.

**Comment by lopatovsky** [comment]
WSGI

``` python
import sys
path = '/home/jamaisvu/MI-PYT'
if path not in sys.path:
    sys.path.append(path)

from app import app as application
```

posledny commit je aktualna veriza

**Comment by hroncok** [comment]
V posledním commitu nemáš žádné `app.py`, ze kterého by se mohl importovat `app`. Zkus:

``` python
...
from twitter_wall import app as application
```

**Comment by hroncok** [comment]
Zkusil jsem to popsat lépe v https://github.com/cvut/MI-PYT/pull/20 - je to srozumitelnější?

**Comment by lopatovsky** [comment]
Ano teraz je to zrejmejsie,
beztak to bola moja hlupa chyba.
Dakujem!

**Comment by hroncok** [comment]
Chyba není hloupá, pokud se z ní něco naučíme.
