### ISSUE TITLE
GitHub label bot: výchozí routa

### ISSUE THREAD

**Issue by hroncok** [cvut/MI-PYT#22]
Kdo dělá GitHub label bota, má v zadání:

> Ve výchozí routě / by aplikace měla informovat uživatele, jak lze použít.

To je proto, abyste také  použili šablony a HTML. Mít tam routu, která vrátí plain-text string není účelné.

Dopíšu do zadání, že by mělo jít o jednoduchou HTML stránku. Omlouvám se, že to měním až takhle, ale bylo to tak myšleno celou dobu, jen to nebylo dost dobře napsané.

Díky za pochopení.

cc @bogdanbodnar @pajcak @chmelva4 @pklejch @melkamar @pilatcen @tulinkry @bobirdmi @krestfi1 @nzt4567 @matejekm @slowbackspace @tomanj23 @Fanarim

**Comment by hroncok** [comment]
Pro tip: Pokud máte Markdown v README a chcete ho načíst a použít, můžete se inspirovat tady:

https://github.com/fedora-python/fedoralovespython.org/blob/b5f16a72fae27f94d6b04905bbcec519d8f59bbb/site.py#L27

**Comment by encukou** [comment]
Pro tip k pro tipu: markdown je potřeba nainstalovat (`python -m pip install markdown`).
