### ISSUE TITLE
Spracovanie entít

### ISSUE THREAD

**Issue by jozefvi94** [cvut/MI-PYT#24]
Možno sa to spomínalo na cviku a už som zabudol, ale čo presne si mám predstaviť pod spracovaním entít pri tom webovom rozhraní twitterwallu?

**Comment by encukou** [comment]
Z odkazů, uživatelů, hashtagů udělat HTML odkaz; obrázky ukázat přes `<img>`.

**Comment by hroncok** [comment]
V tom objektu s tweetem, který je uložený v JSONu, je atribut `entities`, který obsahuje tyto údaje. Není žádoucí odkazy,  uživatele, hashtagy... parsovat z textů tweetů.
