### ISSUE TITLE
Nastavení webové verze Github label bota

### ISSUE THREAD

**Issue by chmelva4** [cvut/MI-PYT#25]
Lze ke githubovému webhooku připojit vlastní payload kromě secret? Nemohl jsem nic takového najít. Jde mi o nastavení pravidel pro webovou verzi, aby se to nemuselo pořád deployovat, jinak budu asi řešit uploadem souboru.

**Comment by hroncok** [comment]
Nejde to. Místo uploadu by to mohl by například v repozitáři v defaultní branchi nějaký soubor .label_rules.cfg, který by sis mohl pokaždé čeknout a přečíst.
