### ISSUE TITLE
Moduly: Další věci

### ISSUE THREAD

**Issue by hroncok** [cvut/MI-PYT#28]
- [x] requirements.txt
- [ ] wheel
- [x] `if __name__ == '__main__'`
- [x] `__main__.py`
- [ ] <del>Něco k verzím. Dev, alfa, beta. Že úkol by měl mít verzi 0.3 jako tag.</del>
- [x] .pypirc na Windows
- [ ] <del>`maintainer`, `maintainer_email`</del>

**Comment by encukou** [comment]
A dalsi, nez zapomenu: **main**.py, .pypirc na Windows

**Comment by hroncok** [comment]
Něco k verzím. Dev, alfa, beta. Že úkol by měl mít verzi 0.3 jako tag.

**Comment by jirutka** [comment]
Většinou se do názvu tagu označující verzi dává prefix „v“ (např. v0.3), aby to bylo jasně odlišené od příp. ostatních tagů nebo větví.

**Comment by hroncok** [comment]
Jo, tag je zadaný jako v0.3

**Comment by jirutka** [comment]
V textu není moc vysvětlené, co přesně dělá `__init__.py`. Je to záměr s tím, že to jen řeknete?

**Comment by hroncok** [comment]
Záměr to nebyl.

**Comment by encukou** [comment]
další: `maintainer`, `maintainer_email`

**Comment by hroncok** [comment]
Otevřeno jako https://github.com/pyvec/naucse.python.cz/issues/173
