### ISSUE TITLE
Spouštění package jako skriptu a nastavení autentifikace

### ISSUE THREAD

**Issue by melkamar** [cvut/MI-PYT#32]
Jak má správně probíhat spouštění package (nainstalované přes pip) jako skriptu? Doteď to bylo:
1. git clone repo
2. ručně editovat auth config
3. spustit skript

Když si ale package nainstaluju pomocí pip, tak se mi tyhle auth soubory vybalí kdovíkam a nepřijde mi moc user friendly upravovat je někde v site-packages. 

Uživatel může sice parametrem říct, kde se soubor nachází, ale to by ho musel nejdřív nějak získat. Jak na to?

**Comment by hroncok** [comment]
Přijde mi, že nejlepší by bylo při nezadání konfiguračního souboru jako parametr z řádky říct uživateli, jak takový soubor má vypadat. Samozřejmě na to neexistuje jedno jediné správné řešení.

**Comment by jirutka** [comment]
Další možnost je přidat do programu příkaz, který ten soubor vygeneruje (třeba jen základní kostru). V každém případě musí být v návodu (readme) zdokumentovaný.

Jinak doporučené výchozí umístění pro uživatelské konfigurace se liší v závislosti na systému; v Linuxu je to adresář `~/.config`, na OS X `~/Library/Preferences` nebo `~/.config`.

**Comment by hroncok** [comment]
K tomu config diru se hodí nějaká knihovna, třeba https://pypi.python.org/pypi/appdirs
