### ISSUE TITLE
Nechci __main__.py v helpu

### ISSUE THREAD

**Issue by dstlmrk** [cvut/MI-PYT#33]
Je nějaká možnost zbavit se jednoduše `__main__.py` v helpu při volání `python -m twitterwall`? Entry point funguje standartně.

```
$ twitterwall
Usage: twitterwall [OPTIONS] COMMAND [ARGS]...
```

```
$ python -m twitterwall 
Usage: __main__.py [OPTIONS] COMMAND [ARGS]...
```

**Comment by hroncok** [comment]
http://stackoverflow.com/a/32556803/1839451
