### ISSUE TITLE
GitHub issues bot: Testovací repozitář

### ISSUE THREAD

**Issue by hroncok** [cvut/MI-PYT#34]
Ahoj, kdo děláte GitHub issues bot, mohli byste mi prosím vždy říct, kde je nějaký repositář, kde můžu zakládat issues, abych vyzkoušel, že váš deploy funguje? Naivně jsme si myslel, že vašeho bota pustím do svého repozitáře, ale chodí mu pozvánka e-mailem a bot nemá přístup, dokud tam nezakliknete _Accept invite_. Když už tedy vyžaduji akci od vás, bude pro mě jednodušší, když mě pustíte do repozitáře, na kterém jste to třeba sami zkoušeli.

Díky a omlouvám se za zmatky.

**Comment by ghost** [comment]
Ahoj,
mel by jsi tam mit pozvanku do testovaciho repozitare. Na dalsim cviku
bych te zase odeberal - at zbytecne nespamuju.

Testrepo:  https://github.com/krestfi1/testrepo
Applikace: http://guynqortgiin9g.pythonanywhere.com/
Webhook: http://guynqortgiin9g.pythonanywhere.com/github_hook
