### ISSUE TITLE
Instalace přes pip (testovací PyPi)

### ISSUE THREAD

**Issue by ggljzr** [cvut/MI-PYT#35]
Já mám menší problém s instalací balíčku pomocí pipu z testovací PyPi. Když projekt stáhnu z githubu a nainstaluju pomocí setup.py install, tak všechno funguje jak má.

Stejně tak funguje instalace pomocí pipu, když použiju přímý link na archiv s projektem, tedy

```
python -m pip install https://testpypi.python.org/packages/.../pytwitter-0.3.3.tar.gz
```

Když ale zkusím balíček nainstalovat přímo, tedy:

```
python -m pip install -i  https://testpypi.python.org/pypi pytwitter
```

vypíše program chybu při řešení závislostí:

```
Could not find a version that satisfies the requirement Flask>=0.11.1 (from pytwitter) (from versions: )
No matching distribution found for Flask>=0.11.1 (from pytwitter)
```

Verze použitých modulů jsem získal pomocí pip freeze, předpokládám teda, že problém je v tim přepínači -i https://testpypi... . Ještě jsem zkoušel přepínač --extra-index-url, tedy:

```
python -m pip install --extra-index-url  https://testpypi.python.org/pypi pytwitter
```

Ten však nainstaluje nějaký uplně jiný projekt než můj :-) (hádám, že jde o konflikt názvů projektů na normální a testovací PyPi). 

Měl bych tedy změnit verze potřebných modulů (například při změně verze Flasku na 0.10 tahle závislost projde, ale spadne to hned na další (click 6.6)), přejmenovat projekt na něco jiného a nahrát ho znova nebo použít nějaký jiný přepinač pipu pro instalaci z testovací PyPi?

(všechny instalace jsem testoval na novém, prázdném virtuálním prostředí)

**Comment by slowbackspace** [comment]
Skús -i https://testpypi.python.org/pypi --extra-index-url https://pypi.python.org/pypi/

**Comment by ggljzr** [comment]
Tak

```
python -m pip install -i  https://testpypi.python.org/pypi --extra-index-url https://pypi.python.org/pypi pytwitter
```

taky nainstaluje ten pytwitter z normálni pypi a ne ten můj (asi kvůli prioritě nebo proto, že ten na tý normální má vyšší verzi).

**Comment by hroncok** [comment]
A co tohle:

```
python -m pip install -i  https://testpypi.python.org/pypi \
--extra-index-url https://pypi.python.org/pypi pytwitter==0.3.3
```

U mě to funguje :)

**Comment by ggljzr** [comment]
Hmm to mě mělo napadnout, to funguje :-). Takže ten problém s duplicitním názvem projektu mám nějak řešit nebo to už mám nechat jak to je?

**Comment by hroncok** [comment]
Záleží, jestli chceš někdy v budoucnu projekt dát na normální pypi. Pokud ano, řeš to a na normální pypi projekt aspoň zaregistruj. Pokud ne, neřeš to.

**Comment by encukou** [comment]
Na takovouto kolizi jsme nemysleli, omlouvám se. Díky za příkladné nahlášení chyby.

Znovu otevírám, protože bychom v materiálech měli ukázat jak se nastaví _testovací_ PyPI jako extra index:

```
python -m pip install --extra-index-url https://testpypi.python.org/pypi pytwitter==0.3.3
```

Takhle bude mít ostrá PyPI prioritu, takže když někdo nahraje na testovací PyPI nějaký škodlivý balíček se jménem `flask`, nenainstaluje se.

**Comment by hroncok** [comment]
@slowbackspace @ggljzr Nechce poslat do materiálů pull request? Díky

**Comment by hroncok** [comment]
Díky všem

**Comment by hroncok** [comment]
Ten zásadní problém je v tom, že když se použije testpypi, tak se odtamtud
stahují i ty dependence. A evidentně je to tam s nimi v dost špatném stavu,
čemuž se nejde divit, když je to testovací pypi.

Použít extra pypi přepínač je tedy asi lepší, ale kolize jmen to znemožňuje.

Pokud v budoucnu plánuješ nahrát projekt na opravdovou pypi, tak by bylo
asi nejlepší ho přejmenovat a jméno si tam zabrat.

Pokud ne, nejspíš to asi neřeš a tenhle issue s popisem problému budeme
brát v potaz při hodnocení (tzn. bude nám stačit, že to je na testovací
pypi a jde to nainstalovat přímým odkazem).
