### ISSUE TITLE
Jak rozbalit README.md a další soubory při pip install?

### ISSUE THREAD

**Issue by melkamar** [cvut/MI-PYT#37]
Ve web módu zobrazuju v default routě obsah `README.md`. Tohle ale nefunguje při spouštění po `pip install`, jelikož `README.md` hledám u `.py` souborů. Obsahem `(...)/site-packages/mypkg/` jsou jen `.py` soubory, ale já tam potřebuju i to readme, html, css atd. Jak zařídit, aby se při instalaci package rozbalilo všechno? 

Našel jsem parametr pro `setup.py: include_package_data`, ale ani to nepomohlo, v `site-package` pořád nic není.  (http://flask.pocoo.org/docs/0.11/patterns/distribute/)

**Comment by dstlmrk** [comment]
https://docs.python.org/3.4/distutils/setupscript.html#installing-package-data

**Comment by dstlmrk** [comment]
Ještě mě napadá, že ne všechno bys měl chtít v `.../sites-packages/mypkg`. Tam by podlě mě měly být pouze soubory potřebné pro běh aplikace. Aspoň jsem to tak vykoukal z ostatních balíků. Možná mě @hroncok vyvede z omylu.

**Comment by melkamar** [comment]
Šel jsem si odpovědět sám, ale jsi rychlejší :)

Já použil tohle:

```
data_files=[("", ["README.md", ]),
                ("bot/static/css", [
                    "static/css/bootstrap.css",
                    "static/css/bootstrap.min.css",
                ]),
                ("bot/templates", [
                    "templates/about.html"])],
```

.. je jeden z těchhle dvou způsobů preferovaný?

**Comment by hroncok** [comment]
Podle https://packaging.python.org/distributing/#package-data a sekce pod tím bych řekl, že pro tohle je preferované `package_data`.

**Comment by ggljzr** [comment]
A co `include_package_data=True` v setup.py a

```
recursive-include yourapplication/templates *
recursive-include yourapplication/static *
```

v MANIFEST.in, jak to píšou na http://flask.pocoo.org/docs/0.11/patterns/distribute/ ?

**Comment by melkamar** [comment]
@ggljzr to jsem zkusil, ale nic se nerozbalilo

**Comment by melkamar** [comment]
@dstlmrk jak vypadá ta syntaxe, která ti zafungovala? Ať dělám, co dělám, tak se mi žádný soubory nekopírujou.. 

```
package_data={'github_issues_bot': ['README.md']},
```
- README.md mám jak v rootu projektu, tak přímo u souboru (kvůli testování), nic se neděje

**Comment by ggljzr** [comment]
Já to mám tak jak jsem psal a `templates` a `static` se mi rozbalí do `.../env/lib/python3.5/site-packages/nazev_balicku`.  Ještě možná blbá připomínka, ale já nejdřív zapoměl přepsat to `yourapplication` v tim MANIFEST.in když sem to kopiroval z tý flask dokumentace.

Jestli ale potřebuješ něco jinýho, tak sem ten původní post špatně pochopil, sorry.

**Comment by melkamar** [comment]
Jo, už. Já měl totiž ty svoje soubory mimo složku/package. Když je přesunu dovnitř, tak už se rozbalí správně.

Akorát README.md potřebuju mít mimo package, ale zároveň ho rozbalit. Takový ohack, kdyby někdo taky potřeboval:

```
import os
import shutil

shutil.copy("README.md", "mypkg/")

setup(
    # ...
)

os.remove("mypkg/README.md")
```

**Comment by dstlmrk** [comment]
@melkamar: Mám to takhle:

```
package_data={
        'pytwitterwall': [
            'static/bootstrap.min.css',
            'templates/pytwitterwall.html'
        ]
    },
```

Nenapadá mě, jak do toho vložit soubor z rootu, já to nepotřeboval, protože si furt myslím, že tam ten README nepatří :smile:

**Comment by hroncok** [comment]
@melkamar to prosím nikdy nedělej. když zavolám `python setup.py --help`, nemělo by to mít žádné následky.

@dstlmrk má pravdu, že tam ten README nepatří. byl to jen pro tip k tomu, jak získat nějaký obsah to routy `/`. Pokud už to tak je, asi bych dal ten README.md dovnitř balíčku a cen z balíčku bych na nějak udělal symlink.
