### ISSUE TITLE
Chyba spusteni balicku pri urcitem prikazu

### ISSUE THREAD

**Issue by bobirdmi** [cvut/MI-PYT#38]
Porad mam nasledujici chyby:
"python -m my_module web"  pada s "**SystemError: Parent module '' not loaded, cannot perform relative import**". Pricemz, pri vymene _web_ za _console_ program funguje bez chyb.

"entry_point web" pada s "**python can't open file '...\envs\mipytcvut\Scripts\githubbot': [Errno 2] No such file or directory**". Avsak soubor "...\Scripts\githubbot" existuje. Entry pointem je _githubbot_. To same, ale s prikazem _console_ opet kupodivu funguje.

Mam Windows.

Nejaka rada?

**Comment by melkamar** [comment]
Mám stejný problém. 

Pokud používám všechno z jednoho souboru, je to ok. Web mám ale v odděleném modulu a když ho chci použít (tj. web command), skončím stejně.

Pokud pouštím skript z nainstalovaného balíku, pak to funguje bez problémů.

**Comment by melkamar** [comment]
@bobirdmi zkus v `__main__.py` importovat absolutní cestu. Zatím to testuju, ale vypadá to, že můj problém to opravilo:

V materiálech je sice

```
from .holidays import main
```

ale když místo toho udělám

```
from somemodule.holidays import main
```

tak to začne jít. 
Ping @hroncok

**Comment by bobirdmi** [comment]
Parada, relativni cesty mam taky vyreseno. Ale ten druhy problem s neexistenci souboru zustal. Kdyz spustim primo ten soubor (githubbot) z adresare _Scripts_ s prikazem _web_ vyhodi stejnou vyjimku, jakoby TENTO soubor neexistuje.

**Comment by hroncok** [comment]
@bobirdmi U tebe vidím problém v tom, že přímo v `__main__.py` definuješ funkce a potom je někde importuješ. V tom souboru bys měl jen něco volat (např funkci `main()`), nic víc. Nevím, jestli to souvisí.

**Comment by hroncok** [comment]
@melkamar Myslím si, že tvoje problémy by mohl způsobovat cyklický import, do kódu jsem ti hodil komentáře na patřičná místa.

**Comment by hroncok** [comment]
Jinak @encukou zná importlib popředu i pozpátku, takže vám poradí lépe.

**Comment by melkamar** [comment]
Dík, cyklický import tam mám, šlo by to refaktorovat, ale myslel jsem si, že by si s tím python mohl poradit.

**Comment by hroncok** [comment]
Jako ono to občas vypadá, že si s tím nějak poradí, ale zrovna u cyklických `from a import b` je to trochu horší. Long story short, nedělá se to.

**Comment by bobirdmi** [comment]
@hroncok Bohuzel chyba s tim nesouvisela. Mozna to je chyba Windows, zkusim zitra naistalovat VirtualBox a spustit program na Ubuntu.

**Comment by hroncok** [comment]
@bobirdmi Na Linuxu mi to při `githubbot web` zůstane viset, nejspíš zacyklené nebo tak něco.

**Comment by hroncok** [comment]
Beru zpět, normálně to běží, jen to loguje do souboru, takže jsem si myslel, že to nic nedělá.

**Comment by bobirdmi** [comment]
Diky moc, 
tedy je problem s Windows. Hodnotit, doufam, budete na Linuxu?

**Comment by hroncok** [comment]
Ano. Kde ale přesně problém leží, ti bohužel nedokážu poradit. Možná @encukou.

**Comment by encukou** [comment]
Chyba `Parent module '' not loaded, cannot perform relative import` nastane, když se snažíš udělat relativní import (`from .holidays import main`), ale nejsi v podmodulu. Například když spustíš přímo `python isholiday/__main_.py`, Python to bere jako _top-level_ modul.

S cyklickými importy si Python poradí tak, že načte kousek jednoho modulu, pak modul druhý, a nakonec dokončí ten původní. Stává se tedy, že část modulu (typicky všechny funkce za cyklickým importem) ještě nejsou nadefinovány, když jsou v druhém modulu potřeba. Zájemce o detaily odkážu na [tuhle svoji přednášku](https://www.youtube.com/watch?v=xm3nkXvUJ2k). Tl;dr: cyklické importy nedoporučuju.

Poslední problém se mi nepodařilo zreprodukovat. Můžeme se na to podívat na cvičení.
