### ISSUE TITLE
Na co je vubec urcen argument "setup_requires" v setup.py?

### ISSUE THREAD

**Issue by bobirdmi** [cvut/MI-PYT#41]
Kdyz zkusim naimportovat nejaky modul na **zacatku** setup.py a mam _setup_requires=['my_module']_,
_setup_requires_ sice nainstaluje tento modul, ale az pri volani funkce _setup()_. Tedy v okamziku kdyz tento modul potrebuju, neni nainstalovan, a navic kod po funkci _setup()_ je na nic (distribucni balicek uz existuje).

Tedy tento argument je uplne zbytecny?

**Comment by hroncok** [comment]
<del>Funguje to tak, že se setup pouští několikrát (sám od sebe).</del>

<del>Proto pokud to uděláš takhle, mělo by to podle mě fungovat:</del>

``` python
try:
    import foo
    print('we have foo, yay!')
except ImportError:
    foo = None
    print('foo not yet available, bah!')

if foo:
    something = foo.bar()
else:
    something = 'TODO'

setup(
    setup_requires=['foo'],
)
```

<del>Měl bys při instalaci vidět něco jako:</del>

```
...
foo not yet available, bah!
...
we have foo, yay!
...
```

EDIT: Asi kecám.

**Comment by bobirdmi** [comment]
U mne (Windows a Ubuntu) se setup pousti pouze jednou.

**Comment by encukou** [comment]
Jo, Miro kecal. První věc co `setup()` dělá je instalace toho, co je v `setup_requires`, takže pro cokoli co se volá ze `setup()` už je to k dispozici. K určení argumentů té funkce to ale nepomůže. Tenhle problém je jedna z věcí, na kterých teď Python Packaging Authority (PyPA) pracuje.

K úkolu – dej prosím své `setup_requires` do README. Bylo to vysvětlené zmateně, tak to budeme uznávat i tak.

**Comment by hroncok** [comment]
Už vím, proč jsem si to myslel. Použil jsem to zatím jen ve funkci předávané setupu, ne při hodnotě.

**Comment by bobirdmi** [comment]
No, `setup_requires` uz vubec nepouzivam. Ted' mam proste hardcoded _README.rst_. Puvodne jsem chtel automaticky generovat tento soubor, ale to je jenom pomucka pro vyvojare, a mnohem jednoduse a rychleji vygenerovat soubor z prikazove radky.

**Comment by jirutka** [comment]
Vygenerovat ho ručně je sice otázka jednoho příkazu, ale za pár týdnů/měsíců už zapomeneš, že se ten soubor vůbec má přegenerovávat. Lepší je to tedy automatizovat, viz [Have the same README both in Markdown and reStructuredText](https://stackoverflow.com/questions/10718767/have-the-same-readme-both-in-markdown-and-restructuredtext/23265673#23265673).

**Comment by bobirdmi** [comment]
Souhlasil bych s tebou, kdyby se nejednalo o README file v rootu (protoze do toho souboru stejne musis koukat pokazde). Navic, pri instalaci balicku donutis uzivatele nainstalovat moduly (v nasem pripade _pandoc_ a _pypandoc_), ktere vubec nejsou nutne pro beh hlavniho programu. Podle mne je to zbytecne,
i kdyby `setup_requires` importoval modul na zacatku `setup.py` (coz nedela).

**Comment by jirutka** [comment]
> pri instalaci balicku donutis uzivatele nainstalovat moduly (v nasem pripade pandoc a pypandoc), ktere vubec nejsou nutne pro beh hlavniho programu.

Nenutím, samozřejmě. Ty pandoc moduly nemám uvedené v `setup.py`, ale pouze v `requirements-dev.txt`. Je tam fallback, že pokud modul není dostupný, tak to jen vypíše varování.

**Comment by hroncok** [comment]
Jednodušší je mít v repu jen README.rst.

**Comment by viktoradavid** [comment]
Proc :-1: ? GitHub, PyPi i normalni editory rst zvladaji.

**Comment by jirutka** [comment]
Protože reStructuredText je snad nejhorší wiki-like syntaxe, která kdy vznikla…
