### ISSUE TITLE
Vykašlat se na relativní importy

### ISSUE THREAD

**Issue by encukou** [cvut/MI-PYT#44]
Flask debug server s nima má problém, a nejsou nijak výrazně lepší než ty absolutní.

**Comment by encukou** [comment]
Alternativa: Používat flask CLI (`$FLASK_APP`)

**Comment by hroncok** [comment]
Není ten problém i jinde než ve Flasku?

**Comment by encukou** [comment]
Ne, normálně se relativní importy chovají dobře.
Problém Flaskového reloaderu byl, že musel reloadovat *kód který ho spustil*, na což bylo potřeba dost magie. S `$FLASK_APP` reloader pouští aplikaci, což je o dost přímočařejší, tak by importy měly fungovat normálně.

**Comment by hroncok** [comment]
Používáme FLASK_APP.
