### ISSUE TITLE
Použití betamax cassette dvakrát v jednom testu failuje

### ISSUE THREAD

**Issue by melkamar** [cvut/MI-PYT#46]
Potřebuju v testu zavolat dvakrát tu samou betamax cassette, vypadá to takhle:

```
def test_fetch_issues(auth_session):
    response = auth_session.get(fetch_issues_url.format(repository, 'all'))
    issues = github_issues_bot.fetch_issues(repository, 'all', auth_session)
    (...)
```

Tohle mi neprochází, error který dostávám je:
```
E           betamax.exceptions.BetamaxError: A request was made that could not be handled.
E           
E           A request was made to https://api.github.com/repos/melkamar/mi-pyt-test-issues/issues?state=all that could not be found in test_process_issues.test_fetch_issues_label.
E           
E           The settings on the cassette are:
E           
E               - record_mode: none
E               - match_options {'uri', 'method'}.
``` 

Jenže když zakomentuju jakýkoliv z těch dvou řádků (ať první nebo druhý), tak to projde bez problémů. URI i metoda požadavku jsou stejné a jsou v souboru uložené, zkontroloval jsem to. Failuje to jenom když chci záznam použít dvakrát.

Když nastavím betamax, aby HTTP GET opravdu prováděl, tak to projde bez problémů.

Nevíte o nějakém nastavení, co by tohle spravilo?

**Comment by hroncok** [comment]
Provádí se ti dvakrát požadavek na stejné URI (nepočítaje část za `?`) se stejnou metodou?

**Comment by melkamar** [comment]
Ano. Mám vytvořenou jedinou kazetu z jediné testovací metody - tam je uloženo jedno volání. 

Obě metody jsou schopné tuhle kazetu použít, pokud nejsou puštěné dohromady - z toho soudím, že požadavek je opravdu na stejnou URI i se stejnou metodou.

Edit: vygeneroval jsem kazetu voláním jedné a pak i druhé metody a ano, shodují se v `request/method` i `request/uri`.

**Comment by hroncok** [comment]
Defaultně se matchuje kazeta podle těchto dvou věcí. Ale jde to změnit. Zkus se podívat na https://betamax.readthedocs.io/en/latest/matchers.html

**Comment by melkamar** [comment]
Tyhle dvě věci mi matchujou. I při různých matchers se mu nechce použít stejnou kazetu víckrát. Failuje např. i 

```
def test_foo(betamax_session):
    response = betamax_session.get('https://google.com')
    response = betamax_session.get('https://google.com')
```

.. kdybych něco našel, dám to sem vědět.

**Comment by hroncok** [comment]
Myslel jsme, že máš jiný problém. Pokud chceš udělat 2 úplně stejné requesty, zkus https://betamax.readthedocs.io/en/latest/record_modes.html new_episodes

**Comment by melkamar** [comment]
Jo, to bude ono. Dík
