### ISSUE TITLE
Náležitosti ohledně semestrálky

### ISSUE THREAD

**Issue by hroncok** [cvut/MI-PYT#5]
- jaké budou termíny? budeme to nějak fázovat?
- jak ji budeme hodnotit (vzdáleně, se studentem)?
- podle jakých kritérií rozdělíme 50 bodů?

V předmětu MI-RUB (Ruby) minulý rok:
- termín na zvolení zadání cca 10. týden
- v průběhu zkouškového období vypsány zápočtové termíny, kde se odevzdávalo cvičícímu (předem se zaslal odkaz na repo)
- hodnotící kritéria neznám, možná poradí @jnv, @petrpulc, @deric nebo @flexik

**Comment by petrpulc** [comment]
Hodnotící kritéria přibližně:
Funguje? 30%
Je to k něčemu? 10%
Naučil se na tom student něco / je na tom vidět snaha? 30%
Kvalita kódu (letmé prolétnutí zdroje) 20%
Pokrytí testy + dokumentace 10%

Ale letos asi budeme trochu měnit.

**Comment by hroncok** [comment]
> Zápočty z předmětů zimního semestru studenti musí získat do konce výuky zimního semestru – tedy do 8. 1. 2017. Garant předmětu může tento termín pro svůj předmět prodloužit, nejdéle však do konce zkouškového období zimního semestru - 17. 2. 2017. ([zdroj](https://www.fit.cvut.cz/casovy-plan/zs))

Připadá mi nehezké vyžadovat odevzdání semestrálky do konce výukového období, když ještě třeba budeme probírat témata, které k tomu budou pro některé potřeba.

Navrhuji tedy následující termíny:
- Na posledním cvičení (4.1.) musí student mít vybrané a schválené téma
- Odevzdání musí proběhnout do 4.2. (ať máme čas, pokud to všichni odevzdají v den deadlinu)

**Comment by encukou** [comment]
Nechci strávit Vánoce schvalováním semestrálek, takže bych téma dal na předposlední cvičení (21. 12.) Na předposlední lekci (dekorátory, deskriptory, metatřídy) se stejně moc neprobírají věci na kterých by šlo stavět zadání práce.

1.2.-5. 2. se plánuje sprint (a přidružené akce) v Ostravě, na kterých minimálně já nebudu mít moc času odpovídat. Takže odevzdání bych dal do konce ledna.
