### ISSUE TITLE
Pandas read_csv

### ISSUE THREAD

**Issue by ghost** [cvut/MI-PYT#54]
In IPython notebook
https://github.com/cvut/MI-PYT/blob/master/tutorials/06-pandas/pandas-intro.ipynb
you use:

``` python
pandas.DataFrame.from_csv('actors.csv', index_col=None)
```

From docs:

> Docstring:
> Read CSV file (DISCOURAGED, please use :func:`pandas.read_csv` instead).
> ...

**Comment by encukou** [comment]
Díky!
Jak vidno, vyplatí se k funkcím co člověk kdysi používal občas přečíst dokumentaci znovu.
