### ISSUE TITLE
import pandas as pd ...

### ISSUE THREAD

**Issue by janpipek** [cvut/MI-PYT#55]
Můžu jenom drzý a nepodstatný komentář k 6. lekci (protože jako celek je super, stejně jako celý kurz)?

_...Automaticky pouštěné skripty musí být samozřejmě robustní, nástroje ke zkoumání dat ale bývají přívětivé k analytikovi, často na úkor robustnosti nebo „dobrých programátorských mravů”. Například některé operátory tak trochu „hadají”, co uživatel chtěl, a v tutoriálech se setkáte se zkratkami jako import pandas as pd či dokonce from numpy import *. ..._

`from numpy import *` je samozřejmě "nemravný kód" a hádání operátorů leckdy přinese více škody než užitku, ale `import pandas as pd; import numpy as np; from matplotlib import pyplot as plt` jsou natolik obvyklé zkratky, že se vyskytují nejen v tutoriálech, ale i v kvalitních knihovnách na numpy/pandas/... založených (jako seaborn, xarray, ...). Naopak explicitní `pandas.něco` jsem viděl snad poprvé ve vašem tutoriálu. Řekl bych, že v tomto případě konvence je silnější než princip explicitnosti.

Ale je to samozřejmě otázka názoru :-)

**Comment by encukou** [comment]
Drzost je rozhodnně místě! :)

Ano, `pd`, `np` i `plt` jsou ve světě dat velice časté – proto je v materiálech zmiňuju. Kvalitní knihovny, které zmiňuješ, je interně používají, ale všimni si, že je používají (apoň teda doufám) _interně_; do API těch knihoven se nedostaly.

Když budeš psát knihovnu na analýzu dat, a zvlášť když budeš data analyzovat, pravděpodobně použiješ konvence z „datové” komunity. Ale Pandas můžeš použít jako součást projektu, na kterém nepracují datoví analytici. A „normálnímu” Pythonistovi přijde tohle zkracování podivné. Já beru projekt jako součást kurzu, kde zpracování dat hraje malou roli. Proto je to pro MI-PYT nastavené tak, jak je – a z tónu téhle issue soudím, že ti to snad ani tolik nevadí. Samozřejmě je to na hraně.

Naťukáváš trošku větší téma – jak na konvence psaní kódu. Pythoní [PEP8](https://www.python.org/dev/peps/pep-0008/) samozřejmě neřeší všechno, ani to není svatý text tesaný to kamene. Pro reálné projekty dřív nebo později vyvstane otázka, jak odpovídat na takovéhle otázky názoru.
Když začneš na něčem dělat sám, konvence si vymyslíš. Když se ale zapojíš do něčeho existujícího (což je častější případ), musíš používat existující konvence, i když s nimi tak úplně nesouhlasíš. V podobných otázkách názoru má poslední slovo maintainer projektu (což jsme pro úlohy v MI-PYT my).
Když se budeš do nějakého projektu zapojovat, je dobré aktivně myslet na to, že nechceš nezačínat zbytečný [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding), tedy zapojovat ostatní spoluautory do řešení trivialit místo toho, aby se projekt posouval dál. („Zbytečný” je klíčové slovo; někdy je dobré triviality pořešit, ale je to v _mnohem_ méně často než na to má typický člověk chuť.) Když mi reviewer řekne, že řádek moc dlouhý, tak ho zkrátím a nebudu se hádat. A na druhou stranu, když jako reviewer/maintainer uvidím řádek co mi připadá trochu moc dlouhý, nebudu zbytečně lpět na detailech – cíl je fungující a čitelný kód, ne kód který je _byte-by-byte_ shodný s tím co bych napsal já.
Tenhle odstavec prosím ber jako trochu nesouvisející radu do budoucna, ne jako pokárání za tuhle issue – snahy o vylepšení materiálů si cením!

**Comment by janpipek** [comment]
Ok, nerad bych vaši pozornost rozptyloval na detailech, ale přišlo mi to prostě zajímavé - skoro jako bych vyčetl z tutoriálu, že "import pandas as pd" je špatně a že se to nemá dělat, přinejmenším v "opravdových" SW projektech. Tak jen oponuji, že se to dělá a že to imho špatně není. Samozřejmě pro účely vašeho kurzu máte vlastní konvenci a nic proti ní nemám. Jde o to, co si studenti odnesou "do života" :-)

Mimochodem, schválně jsem se podíval a ke svému (a vašemu jistě dvojnásobnému) zděšení jsem zjistil, že: `import seaborn; seaborn.pd.np` je zcela validní a vrací přesně to, co bychom čekali (podobně `matplotlib.pyplot.np` atp.). Reexport modulů je zlo, kterému se bohužel v Pythonu dost pracně vyhýbá, přitom by bylo fajn to dělat (že by tohle byla konstruktivní poznámka? :-))

P.S. Netřeba odpovídat a ztrácet čas. Slibuju, že případná příští issue bude užitečnější.

**Comment by jirutka** [comment]
Také na `import pandas as pd` nevidím nic moc špatného. Doufám, že studenty neodrazujete i od psaní `import ... from ...` a nenutíte je všude psát dlouhatánský kanonický název modulu...? ;)

**Comment by bobirdmi** [comment]
Mne se taky nelibi psat `matplotlib.pyplot.plot()` kdyz zkratka `plt.plot()` (`import matplotlib.pyplot as plt`) velmi zjednodusi a zprehledni pochopeni meho kodu.

**Comment by encukou** [comment]
Reexportu modulů se jde vyhnout celkem snadno – od toho je [v sekci o modulech](https://github.com/cvut/MI-PYT/blob/master/tutorials/03_moduly.md#v%C3%ADce-soubor%C5%AF-s-python-k%C3%B3dem) věta „Do `__init__.py` ideálně nepatří žádný kód kromě tohoto.“

**Comment by janpipek** [comment]
Lze (zejména u tak jednoduchého příkladu, jako je projekt o dvou funkcích). U složitějšího projektu s mnoha podbalíčky a separátně použitelnými moduly je to ale _pracné_ (a že `__all__` v pravém smyslu moduly neschovává, věc jen komplikuje). Proto v tom ani numpy, pandas, ... nejsou konsistentní. Zajímalo by mě, jestli třeba flask je (zběžným pohledem mi přijde, že ano).

Ale je to off-topic, uznávám.
