### ISSUE TITLE
Způsob zakládání repozitářů

### ISSUE THREAD

**Issue by petrpulc** [cvut/MI-PYT#6]
Pokud by existovala vůle držet studenty na fakultním Gitlabu, exitoval (existuje, ale teď moc nefunguje) nástroj Gitman, který dokáže/dokázal vyrobit repozitáře pro celý předmět nebo skupinu podle KOSu, případně aktualizovat.

Bývala to moje semestrálka, ale když by se trochu oprášila, měla by bez problémů fungovat. Psáno v ruby (on rails).

Když by to někoho hodně nebavilo, navrhuji klidně vyrobit nějaký newebový skript.

V každém případě mi ale přijde jednodušší držet si studenty na jednom místě než stále obletovat mnoho serverů nebo neustále pullovat.

**Comment by hroncok** [comment]
Díky. My chceme spíš implicitně tlačit GitHub. Aby se ho naučili používat a
pak třeba i na něm dělali ty open sourcy.
