### ISSUE TITLE
Cython OS X build

### ISSUE THREAD

**Issue by janslifka** [cvut/MI-PYT#61]
S použitím `setup.py` [uvedeného v materiálech](https://github.com/cvut/MI-PYT/blob/master/tutorials/08_cython.md#kompilace-pythonu) mám na OS X problém, že to při kompilaci ignoruje `include_dirs`, i když tam jsou uvedené na obou místech, a tím pádem to nenajde nic z numpy.

Snažil jsem se to nějak vyřešit a po nějaké době jsem dospěl k řešení, které mi funguje:

```python
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize
import numpy


setup(
    ext_modules = cythonize([Extension('maze', ['maze.pyx'], include_dirs = [numpy.get_include()])]),
    include_dirs=[numpy.get_include()]
)
```

Nevím, ale jestli to nemůže způsobit zase nějaké jiné problémy.

**Comment by hroncok** [comment]
Díky. Nechám to tady otevřené. Škoda, že to nefunguje tak, jak by mělo.
