### ISSUE TITLE
PyQt5 resources

### ISSUE THREAD

**Issue by JanJecmen** [cvut/MI-PYT#64]
Ahoj, narazil jsem pri delani ukolu na to, ze kdyz chci v kodu pouzivat obrazky / ui soubory, python je hleda relativne k adresari, ze ktereho ho pustim. Napr.
```
python -m maze  # ok
cd ~
python -m maze  # nenajde maze/grass.svg atd.
```
Vyresil jsem to pomoci resource systemu (http://pyqt.sourceforge.net/Docs/PyQt5/resources.html). V materialech k tomu ale nic neni. Je to dobry zpusob / dela se to jeste nejak jinak?
Diky

**Comment by hroncok** [comment]
V našem řešení to řešíme pomocí funkce, která vrací podle relativní cesty k souboru s naším kódem cestu absolutní.

```python
def get_filename(name):
    return os.path.join(os.path.dirname(__file__), name)
```

Výhoda je, že to není závislé na Qt a jde to dělat i jinde.

**Comment by JanJecmen** [comment]
Ok, pekny trik, dekuju za tip.

**Comment by encukou** [comment]
Resource systém z Qt je ale OK. Hodí se hlavně pokud chci aplikaci distribuovat jako jediný spustitelný soubor (což je ovšem hodně nad rámec tohoto kurzu).
