### ISSUE TITLE
Betamax neukládá cassette pro druhý požadavek ze stejné session

### ISSUE THREAD

**Issue by melkamar** [cvut/MI-PYT#72]
Tématicky je tenhle problém už starší, ale řeším ho teď kvůli semestrálce. 

Nevím jestli dělám někde chybu já, nebo to je takhle by design, ale když si udělám fixture z objektu, který má v sobě `betamax_session` a tu použije dvakrát, tak se při druhém volání neuloží nic do kazety.

Usecase je ten, že se potřebuju autentifikovat přes OAuth, takže mám objekt (dostupný jako fixture), ten v inicializaci `conftest.py` pošle request na autentifikaci (tohle se zapíše do kazety) a potom bych očekával, že ho budu moct dál používat v testu. Jenže když ho v testu použiju na volání dalšího requestu, tak se sice vytvoří kazeta, ale je prázdná.¨

Lépe to asi popsat příkladem, takže tady je minimum (non)working code: 
(odkaz na repo: https://github.com/melkamar/betamax-test )
```
git clone https://github.com/melkamar/betamax-test
cd betamax-test
python -m py.test
```
- po testech bych čekal, že v tests/fixtures/cassettes budou dva soubory a oba budou mít nějaká data. 

... přijde mi, že se to občas chová náhodně, protože aniž bych něco měnil, správně se mi nahrály kazety. Nedovedu si ale vysvětlit proč.

Prosím o nějakou radu :)

**Comment by hroncok** [comment]
Zásadní problém tady vidím v tom, že `betemax_session` je "function scope" fixture. To znamená, že se předpokládá, že se bude ten kód, který `betemax_session` vyváří, volat znovu a znovu při každém testu, který používá (byť tranzitivně) `betemax_session`. Ukládat si `betemax_session` do globálního stavu není tedy podporovaný use case.

Tak, jak je ta fixtura navržená, se předpokládá, že každý test bude mít svou vlastní session a tedy si tvoje `foo_fixture` nesmí ukládat session do globálního stavu. Ostatně, kdybys něco takového chtěl dělat, měl bys správně udělat toto:

```python
@pytest.fixture(scope='module')
def foo_fixture(betamax_session):
    betamax_session.headers.update({'Accept-Encoding': 'identity'})
    foo_object = foo.FooRequestsClass(betamax_session)
    foo_object.init_request()
    return foo_object
```

Ale to nejde, protože ti pytest vynadá:

    ScopeMismatch: You tried to access the 'function' scoped fixture 'betamax_session' with a 'module' scoped request object...

Pokud bys to opravdu nutně potřeboval, musel by sis navrhnout vlastní fixture, např. `betamax_multitest_session`, ale největší problém by nebylo to nakódit, ale vymyslet, do které kazety se uloží ta prvotní oauth komunikace, protože standardně, pokud kazety pojmenuješ podle jména testu, se ta "module scopeed" fixture inicializuje při prvním testu, který ji používá. Takže nainvně si tu oath výměnu uložíš do té kazety k prvnímu testu. Ale ten test nemusí být vždy první (můžu ho vypnout, jet paralelně víc testů, cokoliv). Víceméně bys skončil tak, že nějaký test bude záviset na vykonání testu předchozího, což je antipattern.

Lepší řešení by  bylo uložit si tu oauth komunikaci do speciální dedikované kazety, ale to není tak jednoduché. Šel bych na to asi takhle:

https://github.com/sigmavirus24/betamax/blob/0.8.0/betamax/fixtures/pytest.py#L59

Udělal bych si podobnou fixture jako na odkaze výše a někde uprostřed bych udělal ten oauth a změnil po něm jméno kazety. Jestli to bude fungovat, to nevím.

Opravdová otázka je, proč to potřebuješ. Napadají mě dva důvody:

Nechceš pořád u každého testu opakovat oauth na začátku (rychlost? overhead?). Na to bych se vykašlal to řešit a prostě to dělal pořád znovu a znovu.

Nebo chceš testovat více věcí za sebou, že fungují. V takovém případě bys měl správně udělat dedikovaný test, který testuje, že ty věci jdou za sebou, a ne více testů, které pouštíš za sebou.

Dává to smysl?

**Comment by hroncok** [comment]
Ještě přesně co se u tvého kódu děje u druhého testu.

 1. spouští se druhý test
 2. fixtura `foo_fixture` se inicializuje, ale závisí na `betamax_session`
 3. fixtura `betamax_session` se inicializuje, vytváří prázdnou kazetu
 4. fixtura `foo_fixture` vrátí uložený globální stav s uloženou `betamax_session` **z prvního testu**, nově inicializovanou `betamax_session` z přechozího bodu vůbec nepoužije ani nijak nepředá testu
 5. veškerá HTTP komunikace se uloží do té session z globálního stavu

**Comment by melkamar** [comment]
ad 5. - komunikace se vůbec neuloží, ani do té první. Když to projdu v debuggeru, tak při druhém běhu (testu) je v `session` adapter `<requests.adapters.HTTPAdapter object at 0x04EFE130>` místo původního `betamax.adapter.BetamaxAdapter` - to tipuju znamená, že to jde úplně mimo betamax. 

Důvod, proč jsem to chtěl dělat, je OAuth flow při přihlašování se do Google:

1. Uživatel (developer) otevře URL v browseru, vyskočí na něj klasický dialog "Aplikace xyz chce dělat tohle; Accept/Deny". Po Accept dostane uživatel `code`.
2. Aplikace na základě `client_id`, `client_secret` a `code` získá od Google `access_token` (expirace 1h) a `refresh_token`. V tuhle chvíli je `code` použitý a znovu už nejde použít.
3. Teď aplikace může použít `client_id`, `client_secret` a `refresh_token`, aby získala dočasný `access_token`, na základě kterého může komunikovat s API.

V testech jsem se snažil zkontrolovat:
* Objekt, kterému jsem poskytnul `client_id`, `client_secret` a `code` je schopný se zautentizovat (dostat `refresh_token`)
* Tento objekt mi umí vrátit (vygenerovat) `access_token`
* Na tomto objektu můžu volat API a nebude se mi vracet Unauthorized.

Myslel jsem, že půjde pro celou test session vytvořit jeden objekt, na něm jednou zavolat auth metodu a pak ho ve všech testech už jenom používat. Tedy že pro spuštění testů (skutečných, ne z kazet) bude potřeba zadat trojici `client_id`, `client_secret` a `code`. Když to nepůjde takhle, tak se mi zdá, že bude nutné zadat `client_id`, `client_secret`, `refresh_token` a navíc `code` (pro test té prvotní autentifikace).
