### ISSUE TITLE
naucse.python.cz

### ISSUE THREAD

**Issue by encukou** [cvut/MI-PYT#77]
We're building a new site for Python-related course materials.

Currently, there's not much to see on the home page; we're focusing on the content. I'll be starting to teach a course based on the MI-PYT materials on Tuesday; the page for that is here: http://naucse.python.cz/2017/pyknihovny-brno/

It would be nice to move the tutorials to naucse, so they can be shared more widely and improved in context of other open courses in the Python community. They can be linked from here, in the same way that the [file for pandas](https://github.com/cvut/MI-PYT/blob/master/tutorials/06_pandas.md) links to a Notebook deeper in the repo.
Exercises/projects, on the other hand, are currently out of naucse's scope; those should remain in this repo.

So, I'd like to:
* Create a page on naucse for the 2016 run of MI-PYT
* As I go through the materials, remove them from here and instead link to naucse

Do you think this is a good idea?
Things holding this back:
* [ ] Edux integration
* [x] Maintaining history

**Comment by hroncok** [comment]
The Edux integration is still a must for me. If we can make it work...

Also if we move the content to another repo, I'd very much like to preserve the authorship information and commit history rather than copy pasting the content as it is currently done. We can talk about it on Thursday, if it can wait until then.

**Comment by encukou** [comment]
It can definitely wait.

**Comment by hroncok** [comment]
V jakém stavu jsou zkopírované materiály na naučse? Dají se nahradit tím, co je tady?

**Comment by encukou** [comment]
Ano.
Request a Click jsou na naucse rozdělené a doplněné, takže ty se dají zatím nechat jak jsou a přidat requests+click odtud.

**Comment by hroncok** [comment]
Integrace s Eduxem proběhne ruční synchornizací z naučse (nesjpíš ve formě odkazu a statického PDF).

Vypnul jsem automatikcý deploy a přesunu materiály na naučse. Zadání domácích úloh nechám zde.

**Comment by encukou** [comment]
Dneska v 18:30 učím Flask. Jestli bys to nestihl do cca 16:00, začni prosím až zítra.

**Comment by hroncok** [comment]
Udělám to ve formě pull requestu a v tomto repu vše zůstane, dokud nebude zmergován. Předpokládám, že v takovém případě to s ničím nekoliduje.

**Comment by encukou** [comment]
+1

**Comment by hroncok** [comment]
https://github.com/pyvec/naucse.python.cz/pull/67

**Comment by hroncok** [comment]
"Zazálohoval" jsem současný stav MI-PYT repa do branche b161 (nepoužil jsem tag, kdybychom něco chtěli _náhodou_ upravit). A aktualizoval jsem všechny absolutní odkazy z Eduxu na GitHub, aby ukazovali do té branche.

**Comment by hroncok** [comment]
Linky jsem upravil i na GitHubu v té větvi.
