### ISSUE TITLE
Click/Flask feedback

### ISSUE THREAD

**Issue by encukou** [cvut/MI-PYT#78]
* [x] Twitter auth is needlessly complicated, and it requires giving your a telephone number to Twitter. I think it should come after Github API, as an example of auth problems, rather than people's first look at Web APIs.
* [x] The space in `'token '` for the Github authentication header is far too easy to overlook, there should be a note about it.

* [x] The click example explains just the minimum needed for the project. I'm not convinced that's a good introduction to the library. I've expanded it a bit in http://naucse.python.cz/2017/pyknihovny-brno/intro/click/ (we'll use that, so fixed)

**Comment by melkamar** [comment]
I would mention Click's capability to display and animate a progressbar. It's not an essential feature, but it can make some nice looking UI.

**Comment by hroncok** [comment]
Jen si tady odložím [video z přednášky o Clicku](https://www.youtube.com/watch?v=kRY2UGhjRb0) od @tomasbedrich pro inspiraci.
