### ISSUE TITLE
Úkol na Flask a vazba na Click

### ISSUE THREAD

**Issue by hroncok** [cvut/MI-PYT#81]
Po poslední změně v materiálech pouštíme Flaks pomocí `flask run`. V zadání úkolu na Flask chceme, aby byl použitý click na spuštění webové aplikace. Tato kombinace je zvláštní a je třeba se nad ní přinejmenším zamyslet.

**Comment by MarekSuchanek** [comment]
Spouštění přes `flask run` by mohlo nahradit příkaz navíc přes click. V úkolu na moduly by pak ale asi měly být 2 entrypoints - jeden pro flask app a druhý pro CLI.

**Comment by MarekSuchanek** [comment]
Myslím, že ideální by bylo, aby si udělali basic factory (http://flask.pocoo.org/docs/0.12/patterns/appfactories/). 

Při spuštění pomocí `flask run` použijí výchozí hodnoty (případně z proměnných prostředí) a při použití vlastního příkazu se mohou dodat navíc i pomocí přepínačů a argumentů.
