### ISSUE TITLE
Nové úlohy na ZS 2017/2018

### ISSUE THREAD

**Issue by hroncok** [cvut/MI-PYT#87]
* [x] requests+click: globální management labelů na githubu pro víc projektů @MarekSuchanek 
 * [x] flask: master-to-master replikace labelů @MarekSuchanek 
 * [x] pandas: nějaký standardní dataset, třeba Iris? @encukou 
 * [x] moduly: k úloze requests+click+flask  @MarekSuchanek 
 * [x] testování: k úloze requests+click+flask @hroncok
 * [x] dokumentace: k úloze requests+click+flask   @MarekSuchanek 
 * [x] numpy: wa-tor @hroncok
 * [x] cython: zrychlení wa-tor @hroncok
 * [x] pyqt: editor a vizualizér wa-tor @hroncok
 * [x] asyncio: statistika nad github issues @MarekSuchanek 

----

 * [ ] bonusová úloha: Pandas vizualizace statistiky WaToru @MarekSuchanek

**Comment by hroncok** [comment]
ad asyncio: zapojse je dělaný teď přes graphql. Jako jinou úlohu navrhuju labelord na úrovni I, ale v aiohttp.

**Comment by hroncok** [comment]
@encukou zítra mám Pandas s katedrou matematiky. stihneš úkol, nebo jim mám dát loňský?

**Comment by encukou** [comment]
Doufám že stihnu. (s KAM jsem nepočítal, dokud nebylo docela pozdě :( )

**Comment by hroncok** [comment]
Však v pohodě, proto se ptám.

**Comment by MarekSuchanek** [comment]
asyncio: https://github.com/cvut/MI-PYT/pull/123
