### ISSUE TITLE
Format auth.cfg

### ISSUE THREAD

**Issue by ghost** [cvut/MI-PYT#9]
Jaky ma mit format soubor s auth.cfg? 

Asi chcete testovat trochu automaticky a mit sjednoceny format s API keys by zrejme pomohlo.

Navrhuji INI format parsovatelny `configparser`:

```
[github.com]
key = my_secret_key

[twitter.com]
key = my_secret_key
```

**Comment by slowbackspace** [comment]
Na eduxe je imho použiteľná ukážka. Má nejaký zmysel to meniť?

```
[twitter]
key = D4HJp6PKmpon9eya1b2c3d4e5
secret = rhvasRMhvbuHJpu4MIuAb4WO50gnoQa1b2c3d4e5f6g7h8i9j0

[github]
token = xxxxxxx
```

**Comment by ghost** [comment]
Ah, sorry.

**Comment by hroncok** [comment]
Ale není tma nikde napsané, že by to v úkolu mělo dodržet daný formát.
