### ISSUE TITLE
[Labelord] Cesta k default konfiguraku neexistuje - co potom?

### ISSUE THREAD

**Issue by phandox** [cvut/MI-PYT#98]
Ako sa ma program zachovat ak konfiguracny subor neni zadany na CLI a neexistuje ani defaultny v `./config.cfg` ? Ticho to akceptovat a pracovat s prazdnymi options alebo vyhodit chybu? Zo zadania som to uplne nepochopil. 

Diky.

**Comment by hroncok** [comment]
cc @MarekSuchanek

**Comment by MarekSuchanek** [comment]
Akceptovat... bylo to myšleno tím:

> `./config.cfg` (avšak ani tento soubor nemusí existovat)

Pro první dva příkazy je potřeba pouze token, ten se dá zadat proměnnou prostředí nebo přepínačem a v případě `run` lze použít kombinaci `--token`, `--template-repo` a `--all-repos` tak, že zase není potřeba.

**Comment by vanclmil** [comment]
A jakým způsobem se testům vůbec předává ten context pro click prosím? Konkrétně když to chci přepínačem, tak mi to hlásí.
pytest.py: error: unrecognized arguments: --token

**Comment by MarekSuchanek** [comment]
Testům se nic nepředává, vše si obstarají sami a komunikace neprobíhá s GitHub API, ale pomocí přednahraných komunikačních "kazet". 

Testy se spustí jen pomocí `python -m pytest tests/`, jak je popsáno v https://github.com/MarekSuchanek/labelord_tests/blob/master/README.rst

**Comment by vanclmil** [comment]
Jo tak díky - jen jestli to teda chápu, ty testy vůbec nepracují s funkcí cli(...), ale rovnou s těma list_repos, list_labels a run, kterým předává vlastní kontext ctx, kde už je např. session se kterou pracujeme?

**Comment by MarekSuchanek** [comment]
Pracují jenom s `cli` a přes něj případně s podpříkazy, jako kdyby se to spouštělo normálně, jenom se do `ctx.obj['session']` dává speciální session, která kontroluje komunikaci (používá kazety a případně funguje také jako Spy). Pokud tě to víc zajímá, tak je to v [conftest.py](https://github.com/MarekSuchanek/labelord_tests/blob/master/tests/conftest.py) ve funkci `invoker`. Nicméně o `pytest`, `flexmock` a `betamax` bude ještě cvičení...

Pro víc o testování `click` aplikací: http://click.pocoo.org/5/testing/
