### ISSUE TITLE
[Labelord] Specifikace výpisu programu run

### ISSUE THREAD

**Issue by Wilson194** [cvut/MI-PYT#99]
Chvilku už pročítám zadání a stále mi není jasné, jak má vypadat výstup z programu **run**

Výpis má být v tomto formátu

[TAG1] [TAG2] repoName; labelName; color; {error}

### TAG1:
- ADD ->  přidání štítku do repositáře
- DEL -> smazání štítku z repositáře
- UPD -> změna barvy štítku v repositáři
- LBL -> ????

### TAG2:
- DRY -> pokud je vše v pohodě, ale je přepínač -d/--dry-run
- ERR -> pokud příkaz končí jakoukoliv chybou
- SUC -> vše dopadlo dobře

Krom toho, že netuším co znamená štítek LBL, tak mi ještě není jasné, proč je v ukázce v jednom případně štítek jenom s jinou barvou nejdřív smazán a pak přidám a v druhé ukázce je jeho barva upravena (možná to má něco společného s tou chybou, ale tohle chování moc nechápu)

Díky za radu 
 @hroncok @MarekSuchanek

**Comment by MarekSuchanek** [comment]
Dopsal jsem do zadání vysvětlení tagů a upravil dummy output: https://github.com/cvut/MI-PYT/commit/7da5787fd8de0cae7b8c46eec0d75efdd536ba9f

`LBL` = čtení štítků repozitáře - jen ve spojení s chybou, když nebylo možné získat seznam štítků z repozitáře (a nejde tedy ani začít provádět změny).

Víc příkladů výpisů lze nalézt v testech, konkrétně například v https://github.com/MarekSuchanek/labelord_tests/blob/master/tests/test_run_prints.py
